# Generated by Django 5.2.8 on 2025-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_users_usernam_baeb4b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(unique=True, verbose_name='username'),
        ),
    ]
